create table authority
(
    name varchar(255) primary key
);

create table authority_id
(
    id             varchar(255) primary key,
    authority_name varchar(255) not null,

    CONSTRAINT fk_authority_id_authority FOREIGN KEY (authority_name) REFERENCES authority (name)
);

create table line
(
    id                 varchar(255) primary key,
    name               varchar(255) not null,
    transport_sub_mode varchar(255) not null,
    authority_id_id    varchar(255) not null,

    CONSTRAINT fk_line_authority_id FOREIGN KEY (authority_id_id) REFERENCES authority_id (id)
);

create table municipality
(
    id   varchar(255) primary key,
    name varchar(255) not null
);

create table stop_place
(
    id              varchar(255) primary key,
    description     varchar(255),
    name            varchar(255) not null,
    position        varchar(255) not null,
    municipality_id varchar(255) not null,

    CONSTRAINT fk_stop_place_municipality FOREIGN KEY (municipality_id) REFERENCES municipality (id)
);

-- joining table
create table stops_lines
(
    line_id varchar(255) not null,
    stop_id varchar(255) not null,

    CONSTRAINT fk_stops_lines_line FOREIGN KEY (line_id) REFERENCES line (id),
    CONSTRAINT fk_stops_lines_stop_place FOREIGN KEY (stop_id) REFERENCES stop_place (id)
);

create table zone
(
    id             varchar(255) primary key,
    name           varchar(255) not null,
    authority_name varchar(255) not null,

    CONSTRAINT fk_zone_authority FOREIGN KEY (authority_name) REFERENCES authority (name)
);

-- joining table
create table stops_zones
(
    zone_id varchar(255) not null,
    stop_id varchar(255) not null,

    CONSTRAINT fk_stops_zones_zone FOREIGN KEY (zone_id) REFERENCES zone (id),
    CONSTRAINT fk_stops_zones_stop_place FOREIGN KEY (stop_id) REFERENCES stop_place (id)
);

create table zone_connection
(
    id           varchar(255) primary key,
    from_zone_id varchar(255) not null,
    to_zone_id   varchar(255) not null,

    CONSTRAINT fk_from_zone_connection_zone FOREIGN KEY (from_zone_id) REFERENCES zone (id),
    CONSTRAINT fk_to_zone_connection_zone FOREIGN KEY (to_zone_id) REFERENCES zone (id)
);

create table intermediate_zone_alternative
(
    id                 bigint generated by default as identity primary key,
    distance           int          not null,
    zone_connection_id varchar(255) not null,

    CONSTRAINT fk_intermediate_zone_zone_connection FOREIGN KEY (zone_connection_id) REFERENCES zone_connection (id)
);

-- joining table
create table zone_intermediate_zones
(
    zone_id                          varchar(255) not null,
    intermediate_zone_alternative_id bigint       not null,

    CONSTRAINT fk_intermediate_join_zone FOREIGN KEY (zone_id) REFERENCES zone (id),
    CONSTRAINT fk_intermediate_join_alternative FOREIGN KEY (intermediate_zone_alternative_id) REFERENCES intermediate_zone_alternative (id)
);
