name: Gradle Build

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./gradlew clean build
