name: Gradle Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch code
        uses: actions/checkout@v2

      # Install JDK 15
      - name: Setup JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15

      # Cache Gradle Dependencies
      - name: Use cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      # Build
      - name: Build
        run: ./gradlew build -x test

      # Test
      - name: Test
        run: ./gradlew test
